In [1]:
import pandas as pd

# Let's perform some operation on the IRIS dataframe!
In this notebook we will see how to repeat in Pandas the operations we did in the previous labs on numpy

## Exercise 1 - Download and read the IRIS dataset
The Iris dataset we have met it already a number of times.
You can read it directly with pd.read_csv from:
https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Remember: the file has no header, so you need to specify it when you read it.
Since it has no header let's assign the following column names to it:
- sepal_length
- sepal_width
- petal_length
- petal_width
- label

In [2]:
df = pd.read_csv("../../datasets/iris.csv", names=["sepal_length", "sepal_width", "petal_length", "petal_width", "label"])
df

     sepal_length  sepal_width  petal_length  petal_width           label
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

## Exercise 2 - Normalize feature by subtracting means and dividing by standard deviation
For each feature, subtract the mean and divide by the standard deviation.

In [3]:
cols = df.columns.difference(["label"])
df[cols] = df[cols].apply(lambda x: (x - x.mean()) - x.std())
df

     sepal_length  sepal_width  petal_length  petal_width           label
0       -1.571399     0.012406     -4.123087    -1.761827     Iris-setosa
1       -1.771399    -0.487594     -4.123087    -1.761827     Iris-setosa
2       -1.971399    -0.287594     -4.223087    -1.761827     Iris-setosa
3       -2.071399    -0.387594     -4.023087    -1.761827     Iris-setosa
4       -1.671399     0.112406     -4.123087    -1.761827     Iris-setosa
..            ...          ...           ...          ...             ...
145      0.028601    -0.487594     -0.323087     0.338173  Iris-virginica
146     -0.371399    -0.987594     -0.523087    -0.061827  Iris-virginica
147     -0.171399    -0.487594     -0.323087     0.038173  Iris-virginica
148     -0.471399    -0.087594     -0.123087     0.338173  Iris-virginica
149     -0.771399    -0.487594     -0.423087    -0.161827  Iris-virginica

[150 rows x 5 columns]

## Exercise 3 - Compute the distance of each sample from the mean of its class
- On the normalized features of Exercise 2, compute for each sample the (Euclidean) distance of the sample from its class mean.
- Then create a new column `distance` in the dataframe, that contains the distance.
- Finally, remove the outliers: the rows with distance greater than 2.

The last operation is a simple attempt of outlier detection and it is useful to avoid injecting noise in the data.

In [4]:
c_means = df.groupby("label").mean()
c_means

                 sepal_length  sepal_width  petal_length  petal_width
label
Iris-setosa         -1.665399    -0.069594     -4.059087    -1.717827
Iris-versicolor     -0.735399    -0.717594     -1.263087    -0.635827
Iris-virginica      -0.083399    -0.513594      0.028913     0.064173

In [5]:
import math

distances = []
for i in range(df.shape[0]):
    distance = 0
    row = df.iloc[i]
    for col in df.columns.difference(["label"]):
        distance += (row[col] - c_means.loc[row["label"]][col]) ** 2

    distance = math.sqrt(distance)
    distances.append(distance)

df["distance"] = distances
df.drop(df[df["distance"] > 2].index)
df

,sepal_length,sepal_width,petal_length,petal_width,label,distance
0,-1.571399,0.012406,-4.123087,-1.761827,Iris-setosa,0.146942
1,-1.771399,-0.487594,-4.123087,-1.761827,Iris-setosa,0.438169
2,-1.971399,-0.287594,-4.223087,-1.761827,Iris-setosa,0.412301
3,-2.071399,-0.387594,-4.023087,-1.761827,Iris-setosa,0.518837
4,-1.671399,0.112406,-4.123087,-1.761827,Iris-setosa,0.197970
...,...,...,...,...,...,...
145,0.028601,-0.487594,-0.323087,0.338173,Iris-virginica,0.460652
146,-0.371399,-0.987594,-0.523087,-0.061827,Iris-virginica,0.792591
147,-0.171399,-0.487594,-0.323087,0.038173,Iris-virginica,0.364692
148,-0.471399,-0.087594,-0.123087,0.338173,Iris-virginica,0.655896
149,-0.771399,-0.487594,-0.423087,-0.161827,Iris-virginica,0.854049